### ISSUE TITLE
enableItemHorizontalTranslation方法内部的调用错误

### ISSUE THREAD

**Issue by zhCXzhao** [CListery/BottomNavigationEx#12]
```
override fun enableItemHorizontalTranslation(enable: Boolean): BottomNavigationViewEx {
        iBottomNavigationEx.enableLabelVisibility(enable)
        return this
    }
```

**Comment by CListery** [comment]
报错信息贴一下

**Comment by zhCXzhao** [comment]
不是报错，您看下上边我贴的您的源码，您enableItemHorizontalTranslation这个方法中不是要调用fun enableItemHorizontalTranslation(enable: Boolean): IBottomNavigationEx<BNV, BNMV, BNIV>么？

**Comment by zhCXzhao** [comment]
对material1.8.x 1.9.x 还不支持的问题您给我关了，这是另一件事，我贴在这了，问一下后续还会不会继续对 1.8.x 1.9.x 做支持，现在使用material1.8.x 1.9.x 时会报错。

**Comment by zhCXzhao** [comment]
还有另一个事，material1.8.x 1.9.x 不支持的问题您给关了，我就也贴在这说，您后续会对material1.8.x 1.9.x 做支持么？现在使用material1.8.x 1.9.x 会报错，报错信息如下
```
java.lang.RuntimeException: Unable to get provider com.yh.bottomnavigationex.BNVExInit: java.lang.NullPointerException
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7631)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7105)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8059)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:27)
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:19)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils.getVersion$lib_bottomnavigationex_release(MaterialUtils.kt:19)
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils.init(MaterialUtils.kt:15)
                                                                                                    	at com.yh.bottomnavigationex.BNVExInit.onCreate(BNVExInit.kt:10)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7626)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7105) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:257) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:236) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8059) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
```

**Comment by CListery** [comment]
> 不是报错，您看下上边我贴的您的源码，您enableItemHorizontalTranslation这个方法中不是要调用fun enableItemHorizontalTranslation(enable: Boolean): IBottomNavigationEx<BNV, BNMV, BNIV>么？

首先，你标题写的是调用错误，然后现在你又说不是报错，不太能理解你指的是什么问题
第二，你现在所说的结合上下文我也没看懂啥意思

最后，你有没有tg，可以加我 [@clistery](https://t.me/clistery)，直接在线交流会来得快一点

**Comment by CListery** [comment]
> 还有另一个事，material1.8.x 1.9.x 不支持的问题您给关了，我就也贴在这说，您后续会对material1.8.x 1.9.x 做支持么？现在使用material1.8.x 1.9.x 会报错，报错信息如下
> 
> ```
> java.lang.RuntimeException: Unable to get provider com.yh.bottomnavigationex.BNVExInit: java.lang.NullPointerException
>                                                                                                     	at android.app.ActivityThread.installProvider(ActivityThread.java:7631)
>                                                                                                     	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7105)
>                                                                                                     	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978)
>                                                                                                     	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
>                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                                                     	at android.os.Looper.loop(Looper.java:236)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8059)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
>                                                                                                     Caused by: java.lang.NullPointerException
>                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:27)
>                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:19)
>                                                                                                     	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
>                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils.getVersion$lib_bottomnavigationex_release(MaterialUtils.kt:19)
>                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils.init(MaterialUtils.kt:15)
>                                                                                                     	at com.yh.bottomnavigationex.BNVExInit.onCreate(BNVExInit.kt:10)
>                                                                                                     	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
>                                                                                                     	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
>                                                                                                     	at android.app.ActivityThread.installProvider(ActivityThread.java:7626)
>                                                                                                     	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7105) 
>                                                                                                     	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978) 
>                                                                                                     	at android.app.ActivityThread.access$1500(ActivityThread.java:257) 
>                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982) 
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106) 
>                                                                                                     	at android.os.Looper.loop(Looper.java:236) 
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8059) 
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
> ```

首先解释一下，由于 Material 库的特殊性质，大概率是无法做到跨版本兼容的，需要对每个大版本做兼容，所以你提到的 1.7.x 大概率是不会直接能摘 Material 1.8.x 及后续版本运行的，需要单独兼容开发，可以 **`单独`** 对每个版本提需求类的 issue，我有时间的时候会再开发新版本，版本兼容不在这个 issue 讨论

**Comment by zhCXzhao** [comment]
> > 不是报错，您看下上边我贴的您的源码，您enableItemHorizontalTranslation这个方法中不是要调用fun enableItemHorizontalTranslation(enable: Boolean): IBottomNavigationEx<BNV, BNMV, BNIV>么？
> 
> 首先，你标题写的是调用错误，然后现在你又说不是报错，不太能理解你指的是什么问题 第二，你现在所说的结合上下文我也没看懂啥意思
> 
> 最后，你有没有tg，可以加我 [@clistery](https://t.me/clistery)，直接在线交流会来得快一点

很抱歉我描述的不清楚，我直接联系您，麻烦您了

**Comment by zhCXzhao** [comment]
> > 还有另一个事，material1.8.x 1.9.x 不支持的问题您给关了，我就也贴在这说，您后续会对material1.8.x 1.9.x 做支持么？现在使用material1.8.x 1.9.x 会报错，报错信息如下
> > ```
> > java.lang.RuntimeException: Unable to get provider com.yh.bottomnavigationex.BNVExInit: java.lang.NullPointerException
> >                                                                                                     	at android.app.ActivityThread.installProvider(ActivityThread.java:7631)
> >                                                                                                     	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7105)
> >                                                                                                     	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978)
> >                                                                                                     	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
> >                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
> >                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
> >                                                                                                     	at android.os.Looper.loop(Looper.java:236)
> >                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8059)
> >                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
> >                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
> >                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
> >                                                                                                     Caused by: java.lang.NullPointerException
> >                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:27)
> >                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:19)
> >                                                                                                     	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
> >                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils.getVersion$lib_bottomnavigationex_release(MaterialUtils.kt:19)
> >                                                                                                     	at com.yh.bottomnavigationex.MaterialUtils.init(MaterialUtils.kt:15)
> >                                                                                                     	at com.yh.bottomnavigationex.BNVExInit.onCreate(BNVExInit.kt:10)
> >                                                                                                     	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
> >                                                                                                     	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
> >                                                                                                     	at android.app.ActivityThread.installProvider(ActivityThread.java:7626)
> >                                                                                                     	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7105) 
> >                                                                                                     	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6978) 
> >                                                                                                     	at android.app.ActivityThread.access$1500(ActivityThread.java:257) 
> >                                                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982) 
> >                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106) 
> >                                                                                                     	at android.os.Looper.loop(Looper.java:236) 
> >                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8059) 
> >                                                                                                     	at java.lang.reflect.Method.invoke(Native Method) 
> >                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
> >                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
> > ```
> 
> 首先解释一下，由于 Material 库的特殊性质，大概率是无法做到跨版本兼容的，需要对每个大版本做兼容，所以你提到的 1.7.x 大概率是不会直接能摘 Material 1.8.x 及后续版本运行的，需要单独兼容开发，可以 **`单独`** 对每个版本提需求类的 issue，我有时间的时候会再开发新版本，版本兼容不在这个 issue 讨论

好的，谢谢，我关issue了
