### ISSUE TITLE
java.lang.NullPointerException 指针异常

### ISSUE THREAD

**Issue by KnightAndroid** [CListery/BottomNavigationEx#19]
**Describe the bug**
  Process: com.knight.kotlin.wanandroid, PID: 25994
                                                                                                    java.lang.RuntimeException: Unable to get provider com.yh.bottomnavigationex.BNVExInit: java.lang.NullPointerException
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8186)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7722)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7586)
                                                                                                    	at android.app.ActivityThread.access$2600(ActivityThread.java:259)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8673)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:27)
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils$version$2.invoke(MaterialUtils.kt:19)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils.getVersion$lib_bottomnavigationex_release(MaterialUtils.kt:19)
                                                                                                    	at com.yh.bottomnavigationex.MaterialUtils.init(MaterialUtils.kt:15)
                                                                                                    	at com.yh.bottomnavigationex.BNVExInit.onCreate(BNVExInit.kt:10)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2120)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2093)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. oppo]
 - OS: [e.g. Android 11]

**Additional context**
基于Material库 版本1.12.0 依赖了本库2.2.0就报错了 麻烦看看是怎么回事？

**Comment by CListery** [comment]
现在本库支持的 Material 的最高版本为 `1.10.x`，高于该版本暂未适配

**Comment by CListery** [comment]
This issue is stale because it has been open for 14 days with no activity.

**Comment by CListery** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.
