### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot set 'scaleX' to Infinity, the value must be <= 3.4028235E38

### ISSUE THREAD

**Issue by sange93** [CListery/BottomNavigationEx#6]
调用关闭动画binding.navigation.enableAnimation(false)崩溃 ，是什么原因呢？

引入的依赖：
api 'com.google.android.material:material:1.6.1'
implementation 'io.github.clistery:bottomnavigationex-ex:2.0.0'
implementation 'io.github.clistery:bottomnavigationex-16x:2.0.0'

测试机：一加5（Android 10）

错误日志：
java.lang.IllegalArgumentException: Cannot set 'scaleX' to Infinity, the value must be <= 3.4028235E38
                                                                                                    	at android.view.View.sanitizeFloatPropertyValue(View.java:16674)
                                                                                                    	at android.view.View.sanitizeFloatPropertyValue(View.java:16656)
                                                                                                    	at android.view.View.setScaleX(View.java:16009)
                                                                                                    	at com.google.android.material.navigation.NavigationBarItemView.setViewScaleValues(NavigationBarItemView.java:542)
                                                                                                    	at com.google.android.material.navigation.NavigationBarItemView.setChecked(NavigationBarItemView.java:420)
                                                                                                    	at com.google.android.material.navigation.NavigationBarItemView.initialize(NavigationBarItemView.java:194)
                                                                                                    	at com.google.android.material.navigation.NavigationBarMenuView.updateMenuView(NavigationBarMenuView.java:753)
                                                                                                    	at com.google.android.material.bottomnavigation.BottomNavigationViewV16x.enableAnimation(BottomNavigationViewV16x.kt:228)
                                                                                                    	at com.google.android.material.bottomnavigation.BottomNavigationViewV16x.enableAnimation(BottomNavigationViewV16x.kt:35)
                                                                                                    	at com.yh.bottomnavigationex.BottomNavigationViewEx.enableAnimation(BottomNavigationViewEx.kt:126)

**Comment by CListery** [comment]
我使用同样的依赖版本和API尝试复现问题，但并没有出现崩溃。

---

通过对 `com/google/android/material/navigation/NavigationBarItemView.java` 的代码跟踪，

[NavigationBarItemView.java#L659](https://github.com/material-components/material-components-android/blob/948d5dac03a55971338d36bb52f1f49bd448ebd7/lib/java/com/google/android/material/navigation/NavigationBarItemView.java#L659)
```java
private void calculateTextScaleFactors(float smallLabelSize, float largeLabelSize) {
  shiftAmount = smallLabelSize - largeLabelSize;
  scaleUpFactor = 1f * largeLabelSize / smallLabelSize;
  scaleDownFactor = 1f * smallLabelSize / largeLabelSize;
}
```

我发现当只有 `scaleUpFactor` 和 `scaleDownFactor` 这两个值异常时才会出现你所述的问题，你有手动修改过 `smallLabel` 和 `largeLabel` 这两个的字体大小吗？

**Comment by CListery** [comment]
@sange93 Any updates?

**Comment by CListery** [comment]
This issue is stale because it has been open for 14 days with no activity.

**Comment by CListery** [comment]
This issue was closed because it has been inactive for 3 days since being marked as stale.
